# 배포용 앱 도커 + DB 도커
spring:
  datasource:
    url: jdbc:mysql://db:3306/match_prediction?characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

            scope:
              - profile
              - email
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  data:
    redis:
      host: mp-redis
      port: 6379
      timeout: 60000
management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  base64Secret: "Cb2w55+PfHK9R6W6pRujXTxmztcYEx+EA0m92Wys2DDr9s/FVLoDOE8n2jLKf40j4CpbRvTWDRq5dqrhcPCdCw=="
url:
  access-token: https://oauth2.googleapis.com/token
  profile: https://www.googleapis.com/oauth2/v3/userinfo

cookie:
  secure: true
  sameSite: None



